---
- name: uri module demo
  hosts: localhost 
  gather_facts: false
  
 
  vars:
    server: "https://10.10.20.60"
    endpoint: "/token/v2/authenticate"
  tasks:
    - name: login
      ansible.builtin.uri:
        validate_certs: false
        url: "{{ server }}{{ endpoint }}"
        method: POST
        body:
          username: admin
          password: C1sco12345!
        body_format: form-urlencoded
        headers:
          Content-Type: application/x-www-form-urlencoded
        
      register: result

    - name: token
      ansible.builtin.debug:
        var: result.cookies
    
    - name: save cookies
      ansible.builtin.set_fact:
        cookie: "{{ result.cookies }}"
    
    - name: login
      ansible.builtin.uri:
        url: "{{ server }}/sw-reporting/v1/tenants"
        validate_certs: false
        method: GET
        headers:
          Cookie: "{{ cookie}}"
        follow_redirects: safe
        return_content: true
      register: result

    - name: print
      ansible.builtin.debug:
        var: result