---
- name: Dictionary Lookups
  gather_facts: false
  hosts: localhost
  vars: 
    dhcp_servers:
      Location1:
        dhcp_server: dhcp1.domain.com
        scope: 192.168.1.0
      Location2:
        dhcp_server: dhcp2.domin.com
        scope: 192.168.2.0
      Location3:
        dhcp_server: dhcp3.domain.com
        scope: 192.168.3.0
    
    location: 'Location1' # because the location is set to Location1, the set facts template belo will pull out and assign relevant data from the dictionary above.
  tasks:
    - name: Set Facts
      ansible.builtin.set_fact:
        location_dhcp_server:  "{{  item.value.dhcp_server  }}"
        location_dhcp_scope:  " {{  item.value.scope  }}"
      loop: "{{ lookup('dict', dhcp_servers) }}"
      when: "location in item.key"

    - name: Print Facts
      ansible.builtin.debug:
        msg:  
          - "DHCP Server is: {{ location_dhcp_server  }}"
          - "DHCP Scope is: {{ location_dhcp_scope }}"