---
- name: uri module demo
  hosts: localhost 
  gather_facts: false
  vars:
    server: "https://10.10.20.60"
    endpoint: "/token/v2/authenticate"
  tasks:
    - name: login
      ansible.builtin.uri:
        url: "{{ server }}{{ endpoint }}"
        headers:
          Accept:  application/json
          Content-Type:  application/x-www-form-urlencoded
       body_format: json
        body: '{
          "username": "admin",
          "password": "C1sco12345!"
        }'
        method: POST
        validate_certs: false
        timeout: 30
      register: result

    - name: token
      ansible.builtin.debug:
        var: result.cookies